First contribution
zemuldo/iso_8583 pull request #132
Opened 2023-07-26 18:27 UTC by jlaustill

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1PGTK9ip47QNMSbKOVV5OLkDzgpkzmsWk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=qToNpiG)

This PR adds some error handling around the ISO format for healthcare and the ability to leave the 127 field un-expanded and encoded in a customer encoding.

2023-09-14 19:59 UTC, mcfriend99 commented
@zemuldo  Need help with the review??

2023-09-15 04:43 UTC, zemuldo commented
> @zemuldo Need help with the review??

@mcfriend99 Please go ahead. I also plan to have a look this weekend.

2023-09-15 05:04 UTC, zemuldo commented
@jlaustill Please update the change to enable the GitHub actions matrix when you can. I plan to review the PR this weekend.

2023-09-15 14:02 UTC, jlaustill commented
@zemuldo Sorry, I didn't notice the contribution readme :) I'm working with iso packets from Fiserve, and they do a LOT of non standard stuff. So I have this library wrapped by another class that does a tons more to the iso after parsing. Keep that in mind as you review :)

2023-09-18 16:46 UTC, zemuldo commented
Please update the branch you have for tests to run.

2023-09-25 05:25 UTC, zemuldo requested changes
Please add some tests that target the changes you have made.

2025-02-24 14:38 UTC, closed without merging